# Generated by Django 4.2.3 on 2023-08-29 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artshop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='phoneno',
            new_name='PhoneNo',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='emailAddress',
        ),
    ]
