# Generated by Django 4.2.3 on 2023-08-29 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artshop', '0002_rename_phoneno_user_phoneno_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Artworks',
        ),
        migrations.RemoveField(
            model_name='user',
            name='PhoneNo',
        ),
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='emailAddress',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AddField(
            model_name='user',
            name='s1',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='s2',
            field=models.CharField(default='', max_length=200),
        ),
    ]
