# Generated by Django 4.2.3 on 2023-08-29 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artshop', '0006_remove_formation_s1_remove_formation_s2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='Productname',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='formation',
            name='address',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='formation',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
