# Generated by Django 4.2.3 on 2023-08-29 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artshop', '0007_formation_productname_formation_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=200)),
                ('message', models.CharField(default='', max_length=500)),
            ],
            options={
                'db_table': 'contact',
            },
        ),
    ]
