# Generated by Django 4.2.3 on 2023-08-29 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artshop', '0008_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='Artworks',
            field=models.CharField(default='', max_length=100),
        ),
    ]
