# Generated by Django 4.2.3 on 2023-08-30 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artshop', '0010_remove_formation_productname'),
    ]

    operations = [
        migrations.CreateModel(
            name='prod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(default='', max_length=50)),
                ('desc', models.CharField(default='', max_length=250)),
                ('price', models.CharField(default='', max_length=50)),
            ],
            options={
                'db_table': 'prod',
            },
        ),
    ]
