# Generated by Django 4.2.3 on 2023-09-01 06:56

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artshop', '0011_prod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='Artworks',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name'),
        ),
    ]
