# Generated by Django 4.2.3 on 2023-09-01 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artshop', '0012_alter_formation_artworks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='Artworks',
            field=models.CharField(default='', max_length=200),
        ),
    ]
